<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="M705USRA" ignored="0" name="addUser" tests="1" failures="1" timestamp="25 十二月 2018 09:05:18 GMT" time="2.623" errors="0">
  <testcase name="addUser" time="2.579" classname="cases.AddUserTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [true]
	at cases.AddUserTest.addUser(AddUserTest.java:56)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- addUser -->
</testsuite> <!-- addUser -->
